services:
  postgres:
    image: postgres:16-alpine
    container_name: clx_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: clx
      POSTGRES_PASSWORD: clxpassword
      POSTGRES_DB: clx_discord
    ports:
      - "5432:5432"
    volumes:
      - clx_postgres_data:/var/lib/postgresql/data

volumes:
  clx_postgres_data:
